// ENTERPRISE ACTIONS
export const ENTERPRISE_GET_DATA = "ENTERPRISE_GET_DATA";
export const ENTERPRISE_GET_DATA_SUCCESS = "ENTERPRISE_GET_DATA_SUCCESS";
export const ENTERPRISE_GET_DATA_DATABASE = "ENTERPRISE_GET_DATA_DATABASE";
export const ENTERPRISE_GET_DATA_DATABASE_SUCCESS = "ENTERPRISE_GET_DATA_DATABASE_SUCCESS";
export const ENTERPRISE_GET_DATA_DATABASE_FAIL = "ENTERPRISE_GET_DATA_DATABASE_FAIL";
export const ENTERPRISE_GET_DATA_ON_DATABASE = "ENTERPRISE_GET_DATA_ON_DATABASE";
export const ENTERPRISE_GET_DATA_ON_DATABASE_SUCCESS = "ENTERPRISE_GET_DATA_ON_DATABASE_SUCCESS";
export const ENTERPRISE_GET_DATA_STARRED = "ENTERPRISE_GET_DATA_STARRED";
export const ENTERPRISE_GET_DATA_STARRED_SUCCESS = "ENTERPRISE_GET_DATA_STARRED_SUCCESS";
export const ENTERPRISE_GET_DATA_FAIL = "ENTERPRISE_GET_DATA_FAIL";
export const ENTERPRISE_GET_DATA_ON_DATABASE_FAIL = "ENTERPRISE_GET_DATA_ON_DATABASE_FAIL";
export const ENTERPRISE_GET_DATA_STARRED_FAIL = "ENTERPRISE_GET_DATA_STARRED_FAIL";
export const DELETE_ENTERPRISE = "DELETE_ENTERPRISE";
export const DELETE_ENTERPRISE_SUCCESS = "DELETE_ENTERPRISE_SUCCESS";
export const DELETE_ENTERPRISE_FAIL = "DELETE_ENTERPRISE_FAIL";

//ALERT
export const TOGGLE_ALERT = "TOGGLE_ALERT";
